version: v1
mig-configs:
  all-disabled:
    - devices: all
      mig-enabled: false

  migs-with-two-device:
    - devices: [0,1]
      mig-enabled: true
      mig-devices:
        "2g.20gb": 1

  migs-with-one-device:
    - devices: [0]
      mig-enabled: true
      mig-devices:
        "2g.20gb": 2

  all-balanced:
    - devices: all
      mig-enabled: true
      mig-devices:
        "1g.20gb": 1
        "2g.20gb": 3

