version: "3"

services:
  jupyter:
    image: quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.8
    restart: unless-stopped
    ports:
      - 10000:8888
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [compute,utility]
    shm_size: '1gb'
